### ISSUE TITLE
Attack Ranges Failing to Appear

### ISSUE THREAD

**Issue by EpicYoshiMaster** [Corvimae/ranger-routes#7]
Mudkip IVs:
![image](https://user-images.githubusercontent.com/32598419/128218012-c6818288-3bc7-4785-8040-2b37148b2148.png)

Stats for IVs:
(6): 22, 14, 11, 12, 11, 11
(7): 24, 15, 13, 14, 12, 12
(9): 29, 18, 15, 16, 14, 14
(11): 33, 21, 17, 19, 16, 16

Ranges Failing to Appear:

![image](https://user-images.githubusercontent.com/32598419/128217930-8b62944d-731d-47e3-951f-a26120ea0ab3.png)

![image](https://user-images.githubusercontent.com/32598419/128218398-8d804285-4186-4f17-83e1-57beb6a6a95f.png)

**Comment by Corvimae** [comment]
Wrong repo; see https://github.com/Corvimae/pokemon-ranger/issues/11
